version: 2.1

executors:
  flutter-executor:
    docker:
      - image: cirrusci/flutter:latest
    working_directory: ~/project

jobs:
  build:
    executor: flutter-executor
    steps:
      - checkout

      - run:
          name: Cek Struktur Direktori
          command: ls -R

      - restore_cache:
          keys:
            - gradle-cache-v1-{{ checksum "android/build.gradle" }}-{{ checksum "android/app/build.gradle" }}
            - gradle-cache-v1-

      - run:
          name: Set Permission untuk Gradle Wrapper
          command: chmod +x ./android/gradlew

      - run:
          name: Install Dependencies
          command: |
            cd android
            ./gradlew dependencies

      - run:
          name: Build APK Debug
          command: |
            cd android
            ./gradlew assembleDebug

      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-cache-v1-{{ checksum "android/build.gradle" }}-{{ checksum "android/app/build.gradle" }}

      - store_artifacts:
          path: android/app/build/outputs/apk/debug/app-debug.apk
          destination: apk

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
