version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    docker:
      - image: cimg/android:2023.06  # Pastikan image ini cocok dengan lokal

    steps:
      - checkout

      # Cek versi Gradle & Java
      - run:
          name: Check Gradle & Java Version
          command: |
            ./gradlew -v
            java -version

      # Buat apikey.properties dari environment variables
      - run:
          name: Create apikey.properties
          command: |
            echo "API_KEY=${API_KEY}" > apikey.properties
            echo "ANOTHER_SECRET=${ANOTHER_SECRET}" >> apikey.properties

      - run:
          name: Chmod permissions
          command: chmod +x ./gradlew

      # Hapus cache Gradle sebelum build
      - run:
          name: Clean Gradle Cache
          command: |
            rm -rf ~/.gradle/caches
            rm -rf ~/.gradle/wrapper
            ./gradlew clean --no-daemon

      - restore_cache:
          key: android-orb-v1-

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - ~/.android/build-cache
            - ~/.android/cache

      # Langkah Build untuk Hilt
      - run:
          name: Run Hilt Aggregation
          command: ./gradlew app:hiltAggregateDepsDebug --stacktrace

      - run:
          name: Run Hilt Java Compile
          command: ./gradlew app:hiltJavaCompileDebug --stacktrace

      - run:
          name: Run Kapt Debug
          command: ./gradlew kaptDebugKotlin --stacktrace

      # Build Debug
      - run:
          name: Run Debug Build
          command: ./gradlew assembleDebug --stacktrace

      # Build Release (optional)
      - run:
          name: Run Release Build
          command: ./gradlew assembleRelease --stacktrace

      - store_artifacts:
          path: app/build/reports
          destination: reports

      # Jalankan tes lint dan unit test
      - run:
          name: Run Tests
          command: ./gradlew lint test

      - store_test_results:
          path: app/build/test-results

      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file
